# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHSvRmmNm9BW7CnI4n24xgctv-W3HAJd
"""

# ============================================================
# Last Mile Delivery - Streamlit App
# ============================================================
# An interactive web app with two pages:
#   1. Overview   - dashboard showing delivery patterns
#   2. Predictor  - enter delivery details, get a failure risk
#
# How to run locally:
#   pip install streamlit pandas matplotlib joblib scikit-learn
#   streamlit run app.py
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

# --- Corporate colors (same as our charts) ---
DARK_BLUE = "#003366"
MID_BLUE = "#0066CC"
AMBER = "#E8A000"
RED = "#CC0000"
GREY = "#6C757D"


# ============================================================
# Load data and model (cached so it only loads once)
# ============================================================

# @st.cache_data tells Streamlit to remember the result so the
# app stays fast and doesn't reload the file on every click.
@st.cache_data
def load_data():
    return pd.read_csv("data/last_mile_deliveries_clean.csv")

@st.cache_resource
def load_model():
    model = joblib.load("data/delivery_model.pkl")
    columns = joblib.load("data/model_columns.pkl")
    return model, columns

df = load_data()
model, model_columns = load_model()


# ============================================================
# Sidebar - page navigation
# ============================================================

st.sidebar.title("🚚 Last Mile Delivery")
page = st.sidebar.radio("Go to:", ["Overview", "Risk Predictor"])

st.sidebar.markdown("---")
st.sidebar.caption("Built by Chandana Nuthangi")
st.sidebar.caption("from-floor-to-data portfolio")


# ============================================================
# PAGE 1: Overview Dashboard
# ============================================================

def show_overview():
    st.title("Delivery Performance Overview")
    st.write("Understanding where and why last mile deliveries fail.")

    # --- Top row: key numbers (KPIs) ---
    total = len(df)
    failure_rate = (1 - df["delivery_success"].mean()) * 100
    avg_delay = df["delay_minutes"].mean()

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Deliveries", f"{total:,}")
    col2.metric("Failure Rate", f"{failure_rate:.1f}%")
    col3.metric("Avg Delay", f"{avg_delay:.0f} min")

    st.markdown("---")

    # --- Chart 1: Failure rate by zone ---
    st.subheader("Failure Rate by City Zone")
    zone_fail = df.groupby("city_zone")["delivery_success"].apply(
        lambda x: (1 - x.mean()) * 100
    ).sort_values(ascending=False)

    fig, ax = plt.subplots(figsize=(8, 4))
    colors = [RED, AMBER, MID_BLUE, DARK_BLUE]
    ax.bar(zone_fail.index, zone_fail.values, color=colors)
    ax.set_ylabel("Failure Rate (%)")
    for i, v in enumerate(zone_fail.values):
        ax.text(i, v + 0.5, f"{v:.1f}%", ha="center", fontweight="bold")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    st.pyplot(fig)

    # --- Chart 2: Failure rate by weather ---
    st.subheader("Failure Rate by Weather")
    weather_fail = df.groupby("weather")["delivery_success"].apply(
        lambda x: (1 - x.mean()) * 100
    ).sort_values(ascending=False)

    fig2, ax2 = plt.subplots(figsize=(8, 4))
    ax2.bar(weather_fail.index, weather_fail.values, color=MID_BLUE)
    ax2.set_ylabel("Failure Rate (%)")
    for i, v in enumerate(weather_fail.values):
        ax2.text(i, v + 0.5, f"{v:.1f}%", ha="center", fontweight="bold")
    ax2.spines["top"].set_visible(False)
    ax2.spines["right"].set_visible(False)
    st.pyplot(fig2)

    # --- Chart 3: Failure rate by attempt number ---
    st.subheader("Failure Rate by Attempt Number")
    attempt_fail = df.groupby("attempt_number")["delivery_success"].apply(
        lambda x: (1 - x.mean()) * 100
    )

    fig3, ax3 = plt.subplots(figsize=(8, 4))
    ax3.bar(["1st", "2nd", "3rd"], attempt_fail.values, color=[DARK_BLUE, AMBER, RED])
    ax3.set_ylabel("Failure Rate (%)")
    for i, v in enumerate(attempt_fail.values):
        ax3.text(i, v + 0.5, f"{v:.1f}%", ha="center", fontweight="bold")
    ax3.spines["top"].set_visible(False)
    ax3.spines["right"].set_visible(False)
    st.pyplot(fig3)


# ============================================================
# PAGE 2: Risk Predictor
# ============================================================

def show_predictor():
    st.title("Delivery Risk Predictor")
    st.write("Enter the delivery details below to predict the failure risk "
             "**before the driver leaves the depot.**")

    # --- Input widgets, arranged in two columns ---
    col1, col2 = st.columns(2)

    with col1:
        city_zone = st.selectbox("City Zone",
            ["urban_core", "urban_inner", "suburban", "rural"])
        time_window = st.selectbox("Time Window",
            ["morning_08_12", "afternoon_12_17", "evening_17_21", "anytime"])
        weather = st.selectbox("Weather",
            ["clear", "cloudy", "rain", "snow"])
        attempt_number = st.selectbox("Attempt Number", [1, 2, 3])
        driver_experience_yrs = st.slider("Driver Experience (years)", 0.5, 20.0, 5.0)

    with col2:
        package_count = st.slider("Package Count", 1, 12, 3)
        weight_kg = st.slider("Total Weight (kg)", 0.3, 35.0, 5.0)
        distance_km = st.slider("Distance from Depot (km)", 0.5, 60.0, 10.0)
        stops_before_this = st.slider("Stops Before This One", 0, 40, 10)
        traffic_index = st.slider("Traffic Index (1=clear, 10=gridlock)", 1.0, 10.0, 5.0)

    # --- Predict button ---
    if st.button("Predict Risk", type="primary"):

        # Build a single-row input with the same columns as training
        raw_input = {
            "city_zone": city_zone,
            "time_window": time_window,
            "weather": weather,
            "attempt_number": attempt_number,
            "driver_experience_yrs": driver_experience_yrs,
            "package_count": package_count,
            "weight_kg": weight_kg,
            "distance_km": distance_km,
            "stops_before_this": stops_before_this,
            "traffic_index": traffic_index,
        }

        # Encode it exactly like the training data
        input_df = pd.DataFrame([raw_input])
        input_encoded = pd.get_dummies(input_df)
        input_encoded = input_encoded.reindex(columns=model_columns, fill_value=0)

        # Get the failure probability (probability of class 0 = failed)
        classes = list(model.classes_)
        fail_index = classes.index(0)
        failure_risk = model.predict_proba(input_encoded)[0][fail_index] * 100

        # --- Show the result ---
        st.markdown("---")
        st.subheader("Prediction Result")

        # Color the result based on risk level
        if failure_risk >= 60:
            st.error(f"⚠️ HIGH RISK — {failure_risk:.0f}% chance of failure")
            st.write("**Recommendation:** Consider rescheduling, confirming the "
                     "customer is home, or assigning an experienced driver.")
        elif failure_risk >= 35:
            st.warning(f"⚡ MEDIUM RISK — {failure_risk:.0f}% chance of failure")
            st.write("**Recommendation:** Monitor this delivery and have a backup plan.")
        else:
            st.success(f"✅ LOW RISK — {failure_risk:.0f}% chance of failure")
            st.write("**Recommendation:** Proceed as normal.")

        # Show the risk as a progress bar
        st.progress(int(failure_risk))


# ============================================================
# Show the selected page
# ============================================================

if page == "Overview":
    show_overview()
else:
    show_predictor()